apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 10m
  releaseName: kong
  chart:
    spec:
      chart: kong
      version: 2.46.2
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  install:
    createNamespace: true
  values:
    ingressController:
      enabled: true
    proxy:
      type: LoadBalancer
      http:
        enabled: true
      tls:
        enabled: false
    env:
      database: "off"
      log_level: info
